config/routes.rb
Rails.application.routes.draw do
  resources :gyms
  resources :machine_types

end

app/models/gym.rb
class Gym < ActiveRecord::Base
	validates_presence_of :name
end

app/models/machine_type.rb
class MachineType < ActiveRecord::Base
	validates_presence_of :name
	# validates_presence_of :quantity
	# validates :quantity, numericality: { only_integer: true, greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: [:show, :edit, :update, :destroy]

  # GET /gyms
  # GET /gyms.json
  def index
    @gyms = Gym.all
  end

  # GET /gyms/1
  # GET /gyms/1.json
  def show
  end

  # GET /gyms/new
  def new
    @gym = Gym.new
  end

  # GET /gyms/1/edit
  def edit
  end

  # POST /gyms
  # POST /gyms.json
  def create
    @gym = Gym.new(gym_params)

    respond_to do |format|
      if @gym.save
        format.html { redirect_to @gym, notice: 'Gym was successfully created.' }
        format.json { render :show, status: :created, location: @gym }
      else
        format.html { render :new }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyms/1
  # PATCH/PUT /gyms/1.json
  def update
    respond_to do |format|
      if @gym.update(gym_params)
        format.html { redirect_to @gym, notice: 'Gym was successfully updated.' }
        format.json { render :show, status: :ok, location: @gym }
      else
        format.html { render :edit }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyms/1
  # DELETE /gyms/1.json
  def destroy
    @gym.destroy
    respond_to do |format|
      format.html { redirect_to gyms_url, notice: 'Gym was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym
      @gym = Gym.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gym_params
      params.require(:gym).permit(:name, :address, :phone)
    end
end

app/controllers/machine_types_controller.rb
class MachineTypesController < ApplicationController
  before_action :set_machine_type, only: [:show, :edit, :update, :destroy]

  # GET /machine_types
  # GET /machine_types.json
  def index
    @machine_types = MachineType.all
  end

  # GET /machine_types/1
  # GET /machine_types/1.json
  def show
  end

  # GET /machine_types/new
  def new
    @machine_type = MachineType.new
  end

  # GET /machine_types/1/edit
  def edit
  end

  # POST /machine_types
  # POST /machine_types.json
  def create
    @machine_type = MachineType.new(machine_type_params)

    respond_to do |format|
      if @machine_type.save
        format.html { redirect_to @machine_type, notice: 'Machine type was successfully created.' }
        format.json { render :show, status: :created, location: @machine_type }
      else
        format.html { render :new }
        format.json { render json: @machine_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machine_types/1
  # PATCH/PUT /machine_types/1.json
  def update
    respond_to do |format|
      if @machine_type.update(machine_type_params)
        format.html { redirect_to @machine_type, notice: 'Machine type was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine_type }
      else
        format.html { render :edit }
        format.json { render json: @machine_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_types/1
  # DELETE /machine_types/1.json
  def destroy
    @machine_type.destroy
    respond_to do |format|
      format.html { redirect_to machine_types_url, notice: 'Machine type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine_type
      @machine_type = MachineType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_type_params
      params.require(:machine_type).permit(:name, :description, :muscle_group)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/machine_types_helper.rb
module MachineTypesHelper
end

app/views/gyms/_form.html.slim
= form_for @gym do |f|
  - if @gym.errors.any?
    div.alert-box.alert
      h4 = "#{pluralize(@gym.errors.count, "error")} prohibited this gym from being saved:"
      ul
        - @gym.errors.full_messages.each do |message|
          li = message

  .field
    = f.text_field :name, placeholder: "Name"
  .field
    = f.text_field :address, placeholder: "Address"
  .field
    = f.text_field :phone, placeholder: "Phone"
  .actions = f.submit class: 'button'

app/views/gyms/edit.html.slim
h3 Edit

== render 'form'

= link_to 'Show', @gym
'|
= link_to 'Back', gyms_path

app/views/gyms/index.html.slim
h3 Gyms

- @gyms.each do |gym|
  .row
    .small-2.columns
      = link_to gym.name, gym
    .small-4.columns
      = gym.address
    .small-3.columns
      = gym.phone
    .small-3.columns
      ul.button-group
        li = link_to 'Edit', edit_gym_path(gym), class: "button tiny"
        li = link_to 'Delete', gym, data: {:confirm => 'Are you sure?'}, :method => :delete, class: "button tiny alert"

br

= link_to 'New Gym', new_gym_path, class: "button"

app/views/gyms/new.html.slim
h3 New gym

== render 'form'

= link_to 'Back', gyms_path

app/views/gyms/show.html.slim
- if notice
	div.alert-box.success = notice

p
  strong Name:
  = @gym.name
p
  strong Address:
  = @gym.address
p
  strong Phone:
  = @gym.phone

= link_to 'Edit', edit_gym_path(@gym)
'|
= link_to 'Back', gyms_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Gymnasia" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <div class="row">
        <div class="large-12 columns">
          <div class="nav-bar right">
           <ul class="button-group">
             <li><a href="#" class="button">Home</a></li>
             <li><a href="#" class="button">About</a></li>
             <li><a href="#" class="button">Contact</a></li>
            </ul>
          </div>
          <h1>Gymnasia <small>Reserve your gym machines.</small></h1>
          <hr/>
        </div>
      </div>
     
      <div class="row">    
        <div class="large-9 columns" role="content">
          <article>
            <%= yield %>
          </article> 
        </div>
     
        <aside class="large-3 columns">
     
          <h5>Categories</h5>
          <ul class="side-nav">
            <li><a href="#">News</a></li>
            <li><a href="#">Code</a></li>
            <li><a href="#">Design</a></li>
            <li><a href="#">Fun</a></li>
            <li><a href="#">Weasels</a></li>
          </ul>
     
          <div class="panel">
            <h5>Featured</h5>
            <p>Reserve your gym machines now and hit the gym.</p>
            <a href="#">Read More →</a>
          </div>
     
        </aside>    
      </div>

     
      <footer class="row">
        <div class="large-12 columns">
          <hr/>
          <div class="row">
            <div class="large-6 columns">
              <p>© Copyright no one at all. Go to town.</p>
            </div>
            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="#">Link 1</a></li>
                <li><a href="#">Link 2</a></li>
                <li><a href="#">Link 3</a></li>
                <li><a href="#">Link 4</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>

  </body>
</html>

app/views/machine_types/_form.html.slim
= form_for @machine_type do |f|
  - if @machine_type.errors.any?
    div.alert-box.alert
      h4 = "#{pluralize(@machine_type.errors.count, "error")} prohibited this machine_type from being saved:"
      ul
        - @machine_type.errors.full_messages.each do |message|
          li = message

  .field
    = f.text_field :name, placeholder: "Name"
  .field
    = f.text_area :description, placeholder: "Description", rows: 10
  .field
    = f.number_field :muscle_group, placeholder: "Muscle Groups"
  .actions 
    = f.submit class: 'button'

app/views/machine_types/edit.html.slim
h3 Edit

== render 'form'

= link_to 'Show', @machine_type
'|
= link_to 'Back', machine_types_path

app/views/machine_types/index.html.slim
h3 Machine Types

- @machine_types.each do |machine_type|
  .row
    .small-2.columns
      = link_to machine_type.name, machine_type
    .small-6.columns
      = machine_type.description
    .small-1.columns
      = machine_type.muscle_group
    .small-3.columns
      ul.button-group
        li = link_to 'Edit', edit_machine_type_path(machine_type), class: "button tiny"
        li = link_to 'Delete', machine_type, data: {:confirm => 'Are you sure?'}, :method => :delete, class: "button tiny alert"

br

= link_to 'New Machine type', new_machine_type_path, class: "button"

app/views/machine_types/new.html.slim
h3 Define a new kind of machine

== render 'form'

= link_to 'Back', machine_types_path

app/views/machine_types/show.html.slim
- if notice
	div.alert-box.success = notice

p
  strong Name:
  = @machine_type.name
p
  strong Description:
  = @machine_type.description
p
  strong Muscle Group:
  = @machine_type.muscle_group

= link_to 'Edit', edit_machine_type_path(@machine_type)
'|
= link_to 'Back', machine_types_path